CD "%~dp0"
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "AMD64" (GOTO X64)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "ARM64" (GOTO X64)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "X64" (GOTO X64)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "X86_64" (GOTO X64)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "X86-64" (GOTO X64)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "X86" (GOTO X86)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "I386" (GOTO X86)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "I486" (GOTO X86)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "I586" (GOTO X86)
IF /I "%PROCESSOR_ARCHITECTURE%" EQU "I686" (GOTO X86)
:X86
Git-2.45.0-32-bit.exe /SILENT /LOADINF=Config.inf
TortoiseGit-2.16.0.0-32bit.msi /PASSIVE INSTALLDIR="C:\Windows\Git\TortoiseGUI" SSHTOOL="OpenSSH" ALLUSERS=1
EXIT /B
:X64
Git-2.45.0-64-bit.exe /SILENT /LOADINF=Config.inf
TortoiseGit-2.16.0.0-64bit.msi /PASSIVE INSTALLDIR="C:\Windows\Git\TortoiseGUI" SSHTOOL="OpenSSH" ALLUSERS=1
EXIT /B